# Microhackaton 21 CircleCI pipeline
version: 2.1

jobs:
  microhackaton21-job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Permisos y ejecución test
          command: | 
            chmod +x ./tests/test.sh
            ./tests/test.sh
      - run:
          name: Despliegue con Python http.server
          command: |
            python3 -m http.server 8000 --bind 0.0.0.0 &
            sleep 5
          # Para que dé tiempo a arrancar al servidor 
      - run:
          name: Access Python HTTP Server with Curl
          command: |
            curl http://0.0.0.0:8000
workflows:
  despliegue:
    jobs:
      - microhackaton21-job
      
